### PR TITLE
frontend_net: 0 limit means no connections allowed

### PR DESCRIPTION
**Pull request by adamdickmeiss**
For connect-max, connect-total, http-req-max, a limit value of 0 allows no connections rather than any number of connections.

### CODE REVIEW

**Review by wafschneider — COMMENTED** [review]
This looks good, the documentation update is helpful. Do you think we need to mention that the _default_ is unlimited connections?

**Comment by adamdickmeiss** [comment]
> This looks good, the documentation update is helpful. Do you think we need to mention that the _default_ is unlimited connections?

I think that's mentioned on line 73

**Comment by wafschneider** [comment]
> I think that's mentioned on line 73

That's true, and also line 93, though both cases are in reference to the glob matching on the `ip` attribute. The document also doesn't really describe the behavior if the `ip` attribute is omitted (though the example does show it).

I assume my understanding of the behavior is correct -- that if no patterns are matched, the limit for the element with no `ip` attribute is used, or if there is no element without an `ip` attribute there is no limit for that request? Sheesh, that's hard to express.

**Comment by adamdickmeiss** [comment]
> > I think that's mentioned on line 73
> 
> That's true, and also line 93, though both cases are in reference to the glob matching on the `ip` attribute. The document also doesn't really describe the behavior if the `ip` attribute is omitted (though the example does show it).
> 
> I assume my understanding of the behavior is correct -- that if no patterns are matched, the limit for the element with no `ip` attribute is used, or if there is no element without an `ip` attribute there is no limit for that request? Sheesh, that's hard to express.

Ordens matters. At first match the proces stops.

I'll rephrase.

**Comment by wafschneider** [comment]
That looks great, @adamdickmeiss, much more clear. Thank you! I made a couple more minor tweaks. I think this is a good change.

**Pull request merged**
